'use client';
import {useEffect,useState} from 'react';
import {adminRequest} from './request';
import {useStore} from '../providers';
export default function CategoriesPanel(){const {refreshCatalog}=useStore();const [rows,setRows]=useState<string[]>([]),[name,setName]=useState(''),[oldName,setOldName]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{void adminRequest('/api/admin/categories').then(setRows).catch(e=>setError(e.message));},[]);
 async function save(method:string,body:Record<string,string>){setBusy(true);setError('');setMessage('');try{setRows(await adminRequest('/api/admin/categories',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));await refreshCatalog();setName('');setOldName(null);setMessage('تم حفظ الأقسام.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><p>أضف أي قسم تحتاجه، مثل الملابس النسائية أو الملابس الداخلية. يظهر القسم في المتجر وقائمة اختيار قسم المنتج.</p><form onSubmit={e=>{e.preventDefault();void save(oldName===null?'POST':'PATCH',{name,...(oldName===null?{}:{oldName})});}}><label className="field">{oldName===null?'اسم القسم الجديد':'تعديل اسم القسم'}<input required maxLength={100} value={name} disabled={busy} onChange={e=>setName(e.target.value)}/></label><button className="btn" disabled={busy}>{oldName===null?'إضافة قسم':'حفظ الاسم'}</button>{oldName!==null&&<button type="button" className="choice" disabled={busy} onClick={()=>{setOldName(null);setName('');}}>إلغاء</button>}</form>{error&&<p className="notice" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<table><thead><tr><th>القسم</th><th>إجراء</th></tr></thead><tbody>{rows.map(c=><tr key={c}><td>{c}</td><td><button disabled={busy} className="choice" onClick={()=>{setOldName(c);setName(c);}}>تعديل</button> <button disabled={busy} className="choice danger" onClick={()=>{if(window.confirm(`حذف قسم ${c}؟`))void save('DELETE',{name:c});}}>حذف</button></td></tr>)}</tbody></table><p className="muted">تغيير الاسم يحدّث منتجات القسم أيضاً. لا يمكن حذف قسم يحتوي على منتجات.</p></section>;
}
