'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {adminRequest} from './request';
import {useStore} from '../providers';
import {categoryArtwork} from '../theme-art';
import {MAX_IMAGE_BYTES} from '../banner-settings';
type Category={name:string;image:string;customized?:boolean};
export default function CategoriesPanel(){
 const router=useRouter();const {refreshCatalog}=useStore();const [rows,setRows]=useState<Category[]>([]),[name,setName]=useState(''),[oldName,setOldName]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [file,setFile]=useState<File|null>(null),[existing,setExisting]=useState(''),[remove,setRemove]=useState(false),[preview,setPreview]=useState('');const inputRef=useRef<HTMLInputElement>(null);const formRef=useRef<HTMLFormElement>(null);
 const load=async()=>setRows(await adminRequest('/api/admin/categories?details=1'));
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 const reset=()=>{setName('');setOldName(null);setFile(null);setExisting('');setRemove(false);if(inputRef.current)inputRef.current.value='';};
 async function save(method:string,body:FormData|Record<string,string>){setBusy(true);setError('');setMessage('');try{await adminRequest('/api/admin/categories',{method,...(body instanceof FormData?{body}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});await load();await refreshCatalog();router.refresh();reset();setMessage('تم حفظ القسم وصورته.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const image=preview||(!remove?existing:'');
 return <section className="panel"><p>يمكنك تبديل أيقونة القسم أو حذف الأيقونة وحدها دون حذف القسم أو منتجاته.</p><form ref={formRef} onSubmit={e=>{e.preventDefault();const form=new FormData();form.set('name',name);if(oldName!==null)form.set('oldName',oldName);if(file)form.set('image',file);if(remove)form.set('removeImage','true');void save(oldName===null?'POST':'PATCH',form);}}><fieldset className="banner-fields" disabled={busy}><label className="field">{oldName===null?'اسم القسم الجديد':'تعديل اسم القسم'}<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><div className="upload-box"><label className="btn upload-label" htmlFor="category-upload">رفع صورة أو أيقونة القسم</label><input ref={inputRef} id="category-upload" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const chosen=e.target.files?.[0];if(!chosen)return;if(chosen.size>MAX_IMAGE_BYTES||!['image/png','image/jpeg','image/webp'].includes(chosen.type)){setError('اختر PNG أو JPG أو WebP بحجم لا يتجاوز 4 ميغابايت.');e.target.value='';return;}setFile(chosen);setRemove(false);setError('');}}/><p className="muted">مقاس مقترح 512 × 512 بكسل. PNG بخلفية شفافة مناسب للأيقونات. الحد 4 ميغابايت.</p>{image&&<><img className="category-preview" src={image} alt="معاينة صورة القسم"/><button type="button" className="choice danger" onClick={()=>{setFile(null);setRemove(true);if(inputRef.current)inputRef.current.value='';}}>إزالة الصورة عند الحفظ</button></>}</div><button className="btn">{busy?'جارٍ الحفظ…':oldName===null?'إضافة القسم وصورته':'حفظ التعديلات'}</button>{oldName!==null&&<button type="button" className="choice" onClick={reset}>إلغاء</button>}</fieldset></form>{error&&<p className="notice" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<table><thead><tr><th>القسم</th><th>إجراء</th></tr></thead><tbody>{rows.map(c=><tr key={c.name}><td>{c.image?<img className="admin-product-thumb" src={c.image} alt=""/>:!c.customized&&categoryArtwork(c.name)?<span className={"category-photo admin-category-icon art-"+categoryArtwork(c.name)!.slot}/>:null}{c.name}</td><td><button disabled={busy} className="choice" onClick={()=>{reset();setOldName(c.name);setName(c.name);setExisting(c.image);formRef.current?.scrollIntoView({behavior:'smooth',block:'start'});}}>تبديل الأيقونة / تعديل القسم</button> <button disabled={busy} className="choice danger" onClick={()=>{const form=new FormData();form.set("name",c.name);form.set("oldName",c.name);form.set("removeImage","true");void save("PATCH",form);}}>حذف الأيقونة فقط</button> <button disabled={busy} className="choice danger" onClick={()=>{if(window.confirm(`حذف قسم ${c.name}؟`))void save('DELETE',{name:c.name});}}>حذف القسم بالكامل</button></td></tr>)}</tbody></table><p className="muted">لا يمكن حذف قسم يحتوي على منتجات. تبقى صورته محفوظة عند تغيير الاسم.</p></section>;
}
