'use client';
import {FormEvent,useState} from 'react';
import Link from 'next/link';
import {categories,money,Product,provinces} from '../data';
import {useStore} from '../providers';

type Order={id:string;name:string;phone:string;city:string;address:string;landmark:string;total:number;status:string;lines:{name:string;variant:string;qty:number;price:number}[]};
const initialOrders:Order[]=[
 {id:'#1048',name:'سارة محمد',phone:'0770 000 0000',city:'بغداد',address:'المنصور، شارع 14، منزل 7',landmark:'قرب المكتبة',total:180000,status:'جديد',lines:[{name:'أحمر شفاه Rouge',variant:'وردي هادئ • 3.5 غم',qty:2,price:54000},{name:'كريم Moisture Surge',variant:'50 مل',qty:1,price:62000}]},
 {id:'#1047',name:'نور علي',phone:'0750 000 0000',city:'أربيل',address:'عنكاوا، شارع 100',landmark:'مقابل الحديقة',total:250000,status:'مؤكد',lines:[{name:'عطر Libre',variant:'90 مل',qty:1,price:145000}]},
 {id:'#1046',name:'علي كريم',phone:'0780 000 0000',city:'البصرة',address:'العشار، شارع الوطن',landmark:'قرب الصيدلية',total:325000,status:'مكتمل',lines:[{name:'سيروم Advanced Night Repair',variant:'50 مل',qty:2,price:79000}]},
];
const statuses=['جديد','مؤكد','قيد التجهيز','شُحن','مكتمل','ملغي','مرتجع'];
const blankProduct=():Product=>({id:`product-${Date.now()}`,name:'',description:'',brand:'',category:categories[0],price:0,shades:[''],sizes:[''],stock:0,color:'#eaf3ef'});

export default function Admin(){
 const {products,saveProduct,deleteProduct,deliveryFees,setDeliveryFee}=useStore();
 const [tab,setTab]=useState('overview');const [orders,setOrders]=useState(initialOrders);const [search,setSearch]=useState('');const [editing,setEditing]=useState<Product|null>(null);const [selected,setSelected]=useState<Order|null>(null);
 const submitProduct=(event:FormEvent)=>{event.preventDefault();if(!editing)return;saveProduct({...editing,price:Math.max(0,editing.price),stock:Math.max(0,editing.stock),shades:editing.shades.filter(Boolean),sizes:editing.sizes.filter(Boolean)});setEditing(null)};
 return <div className="admin"><aside className="sidebar"><Link href="/" className="logo">nastia</Link><nav><span className="notice">نموذج تجريبي</span>{[['overview','نظرة عامة'],['products','المنتجات'],['orders','الطلبات'],['delivery','التوصيل']].map(([key,label])=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}>{label}</button>)}<Link href="/">واجهة المتجر</Link></nav></aside><main className="adminmain"><div className="notice">لوحة الإدارة تجريبية؛ التغييرات مشتركة مع المتجر خلال الجلسة فقط، ولا يوجد تسجيل دخول أو حفظ دائم أو حماية خادم.</div><div className="title-row admin-title"><h1>{tab==='overview'?'لوحة التحكم':tab==='products'?'إدارة المنتجات':tab==='orders'?'إدارة الطلبات':'رسوم التوصيل'}</h1>{tab==='products'&&<button className="btn" onClick={()=>setEditing(blankProduct())}>+ إضافة منتج</button>}</div>
 {tab==='overview'&&<><div className="stats"><div className="stat">طلبات اليوم<b>24</b></div><div className="stat">مبيعات اليوم<b>{money(1250000)}</b></div><div className="stat">بانتظار التجهيز<b>8</b></div><div className="stat">مخزون منخفض<b>{products.filter((p)=>p.stock<6).length}</b></div></div><section className="panel"><h2>ملخص الأسبوع</h2><div className="chart">{[30,52,66,58,76,95,82].map((height,index)=><div key={index} title={`${height}%`} style={{height:`${height}%`}}/>)}</div></section><Orders rows={orders} onStatus={(id,status)=>setOrders((rows)=>rows.map((row)=>row.id===id?{...row,status}:row))} onSelect={setSelected}/></>}
 {tab==='products'&&<section className="panel"><table><thead><tr><th>المنتج</th><th>الماركة / الفئة</th><th>السعر</th><th>الخيارات</th><th>المخزون</th><th>الإجراء</th></tr></thead><tbody>{products.map((p)=><tr key={p.id}><td>{p.name}</td><td>{p.brand}<br/><span className="muted">{p.category}</span></td><td>{money(p.price)}</td><td>{p.shades.join('، ')}<br/>{p.sizes.join('، ')}</td><td>{p.stock}</td><td><button className="choice" onClick={()=>setEditing({...p})}>تعديل</button> <button className="choice danger" onClick={()=>deleteProduct(p.id)}>حذف</button></td></tr>)}</tbody></table></section>}
 {tab==='orders'&&<><div className="field admin-search"><label htmlFor="order-search">البحث في الطلبات</label><input id="order-search" value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="رقم الطلب أو اسم العميل"/></div><Orders rows={orders.filter((order)=>(order.id+order.name).includes(search))} onStatus={(id,status)=>setOrders((rows)=>rows.map((row)=>row.id===id?{...row,status}:row))} onSelect={setSelected}/></>}
 {tab==='delivery'&&<section className="panel"><h2>رسوم حسب المحافظة</h2>{provinces.map((province)=><div className="sumrow" key={province}><b>{province}</b><div className="field"><input aria-label={`رسوم ${province}`} min="0" type="number" value={deliveryFees[province]} onChange={(e)=>setDeliveryFee(province,Number(e.target.value))}/></div></div>)}<p className="muted">تنعكس القيم فوراً في صفحة إتمام الطلب، وتعود للقيم الأصلية عند تحديث الصفحة.</p></section>}
 {editing&&<div className="modal-backdrop" role="presentation"><form className="modal formgrid" onSubmit={submitProduct} aria-label="نموذج المنتج"><div className="wide title-row"><h2>{products.some((p)=>p.id===editing.id)?'تعديل المنتج':'إضافة منتج'}</h2><button type="button" className="choice" onClick={()=>setEditing(null)}>إغلاق</button></div><Field label="الاسم"><input required value={editing.name} onChange={(e)=>setEditing({...editing,name:e.target.value})}/></Field><Field label="الماركة"><input required value={editing.brand} onChange={(e)=>setEditing({...editing,brand:e.target.value})}/></Field><Field label="الفئة"><select value={editing.category} onChange={(e)=>setEditing({...editing,category:e.target.value})}>{categories.map((x)=><option key={x}>{x}</option>)}</select></Field><Field label="السعر"><input required min="0" type="number" value={editing.price} onChange={(e)=>setEditing({...editing,price:Math.max(0,Number(e.target.value))})}/></Field><Field label="الدرجات (افصلي بينها بفاصلة)"><input required value={editing.shades.join('،')} onChange={(e)=>setEditing({...editing,shades:e.target.value.split(/[،,]/).map((x)=>x.trim())})}/></Field><Field label="الأحجام (افصلي بينها بفاصلة)"><input required value={editing.sizes.join('،')} onChange={(e)=>setEditing({...editing,sizes:e.target.value.split(/[،,]/).map((x)=>x.trim())})}/></Field><Field label="المخزون"><input required min="0" type="number" value={editing.stock} onChange={(e)=>setEditing({...editing,stock:Math.max(0,Number(e.target.value))})}/></Field><Field label="الوصف" wide><textarea required rows={3} value={editing.description} onChange={(e)=>setEditing({...editing,description:e.target.value})}/></Field><button className="btn wide">حفظ المنتج التجريبي</button></form></div>}
 {selected&&<div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="order-title"><div className="title-row"><h2 id="order-title">تفاصيل الطلب {selected.id}</h2><button className="choice" onClick={()=>setSelected(null)}>إغلاق</button></div><p><b>العميل:</b> {selected.name} — {selected.phone}</p><p><b>التوصيل:</b> {selected.city}، {selected.address} ({selected.landmark})</p><h3>المنتجات</h3>{selected.lines.map((line)=><div className="sumrow" key={line.name+line.variant}><span>{line.name}<small className="muted"> — {line.variant} × {line.qty}</small></span><b>{money(line.price*line.qty)}</b></div>)}<div className="sumrow total"><span>إجمالي الطلب</span><b>{money(selected.total)}</b></div></section></div>}
 </main></div>;
}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`field ${wide?'wide':''}`}><span>{label}</span>{children}</label>}
function Orders({rows,onStatus,onSelect}:{rows:Order[];onStatus:(id:string,status:string)=>void;onSelect:(order:Order)=>void}){return <section className="panel"><h2>الطلبات</h2><table><thead><tr><th>الطلب</th><th>العميل</th><th>المحافظة</th><th>الإجمالي</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>{rows.map((order)=><tr key={order.id}><td><b>{order.id}</b></td><td>{order.name}</td><td>{order.city}</td><td>{money(order.total)}</td><td><select className="status" value={order.status} onChange={(e)=>onStatus(order.id,e.target.value)}>{statuses.map((status)=><option key={status}>{status}</option>)}</select></td><td><button className="choice" onClick={()=>onSelect(order)}>عرض</button></td></tr>)}</tbody></table></section>}
