'use client';
import {useEffect,useState} from 'react';
import {adminRequest} from './request';
type Ticket={id:string;name:string;phone:string;order_ref:string;category:string;body:string;status:string;created_at:string;messages:{id:number;sender:string;body:string;created_at:string}[]};
export default function SupportPanel(){const [rows,setRows]=useState<Ticket[]>([]),[selected,setSelected]=useState<Ticket|null>(null),[body,setBody]=useState(''),[status,setStatus]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>setRows(await adminRequest('/api/admin/support'));
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 async function open(id:string){setBusy(true);setError('');try{const item=await adminRequest('/api/admin/support?id='+encodeURIComponent(id));setSelected(item);setStatus(item.status);setBody('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="panel"><p>أحدث 200 طلب دعم وشكوى.</p><button disabled={busy} className="choice" onClick={()=>void load().catch(e=>setError(e.message))}>تحديث</button>{error&&<p role="alert" className="notice">{error}</p>}<div style={{overflowX:'auto'}}><table><thead><tr><th>رقم المتابعة</th><th>الاسم</th><th>النوع</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.id}</td><td>{t.name}</td><td>{t.category}</td><td>{t.status}</td><td><button disabled={busy} className="choice" onClick={()=>void open(t.id)}>فتح</button></td></tr>)}</tbody></table></div>{rows.length===0&&<p>لا توجد طلبات دعم حالياً.</p>}
 {selected&&<div className="modal-backdrop"><section className="modal"><div className="title-row"><h2>طلب الدعم {selected.id}</h2><button className="choice" disabled={busy} onClick={()=>setSelected(null)}>إغلاق</button></div><p>{selected.name} — {selected.phone}</p><p>طلب الشراء: {selected.order_ref||'غير محدد'}</p><p style={{whiteSpace:'pre-wrap'}}>{selected.body}</p>{selected.messages.map(m=><div className="notice" key={m.id}><b>{m.sender}</b><p style={{whiteSpace:'pre-wrap'}}>{m.body}</p><small>{m.created_at} UTC</small></div>)}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await adminRequest('/api/admin/support',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:selected.id,status,...(body.trim()?{body}:{})})});setSelected(result);setBody('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><fieldset className="banner-fields" disabled={busy}><label className="field">الحالة<select value={status} onChange={e=>setStatus(e.target.value)}>{['جديد','قيد المعالجة','محلول'].map(s=><option key={s}>{s}</option>)}</select></label><label className="field">الرد على العميل<textarea maxLength={4000} value={body} onChange={e=>setBody(e.target.value)}/></label><button className="btn">{busy?'جارٍ الحفظ…':'حفظ وإرسال الرد'}</button></fieldset></form>{error&&<p className="notice" role="alert">{error}</p>}</section></div>}</section>;
}
