import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {ensureCategories,listCategories,addCategory,renameCategory,removeCategory} from '../app/category-store.ts';
import {transaction} from '../app/admin-accounts.ts';
import {paginate} from '../app/pagination.ts';
import {can} from '../app/admin-permissions.ts';
test('category migration preserves existing names, renames products, blocks occupied deletion and does not reseed deleted categories',()=>{const db=new DatabaseSync(':memory:');db.exec("CREATE TABLE app_meta(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE products(id TEXT,category TEXT);INSERT INTO products VALUES('a','قديم')");ensureCategories(db,['مكياج']);assert.deepEqual(listCategories(db),['مكياج','قديم']);transaction(db,()=>addCategory(db,'ملابس نسائية'));assert.throws(()=>addCategory(db,'ملابس نسائية'));transaction(db,()=>renameCategory(db,'قديم','جديد'));assert.equal(db.prepare('SELECT category FROM products').get()?.category,'جديد');assert.throws(()=>transaction(db,()=>removeCategory(db,'جديد')));transaction(db,()=>removeCategory(db,'مكياج'));ensureCategories(db,['مكياج']);assert.ok(!listCategories(db).includes('مكياج'));assert.throws(()=>addCategory(db,' '));assert.equal(can('owner','categories'),true);for(const role of ['products','orders','content','support'] as const)assert.equal(can(role,'categories'),false);db.close();});
test('pagination slices after filtering and clamps empty, invalid and reduced pages',()=>{const items=Array.from({length:49},(_,i)=>i);assert.deepEqual(paginate(items,1).items,items.slice(0,12));assert.equal(paginate(items,5).items.length,1);assert.equal(paginate(items,99).page,5);assert.equal(paginate(items.filter(n=>n<3),5).page,1);assert.equal(paginate([],3).total,1);assert.deepEqual(paginate([],3).items,[]);assert.equal(paginate(items,NaN).page,1);const many=paginate(Array.from({length:1000}),50);assert.equal(many.pages.length,7);assert.ok(many.pages.includes(50));});
