import {randomBytes,createHash,timingSafeEqual} from 'node:crypto';
import type {DatabaseSync} from 'node:sqlite';
import {AccountError,transaction} from './admin-accounts.ts';
export const supportStatuses=['جديد','قيد المعالجة','محلول'] as const;
export function ensureSupport(db:DatabaseSync){db.exec(`CREATE TABLE IF NOT EXISTS support_tickets(id TEXT PRIMARY KEY,access_hash TEXT NOT NULL,name TEXT NOT NULL,phone TEXT NOT NULL,order_ref TEXT NOT NULL,category TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'جديد',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS support_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,ticket_id TEXT NOT NULL REFERENCES support_tickets(id),sender TEXT NOT NULL,body TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS support_limits(key TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);`);}
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
export function limitSupport(db:DatabaseSync,key:string,max=10){const now=Date.now();transaction(db,()=>{db.prepare('DELETE FROM support_limits WHERE expires<=?').run(now);const row=db.prepare('SELECT count FROM support_limits WHERE key=?').get(key);if(row&&Number(row.count)>=max)throw new AccountError('محاولات كثيرة. حاول بعد ساعة.',429);db.prepare('INSERT INTO support_limits VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1').run(key,now+3600000);});}
function field(input:Record<string,unknown>,key:string,max:number,optional=false){const value=input[key];if(typeof value!=='string'||value.trim().length>max||(!optional&&!value.trim()))throw new AccountError('أكمل الحقول المطلوبة ضمن الأطوال المسموحة.');return value.trim();}
export function createTicket(db:DatabaseSync,input:Record<string,unknown>){const name=field(input,'name',80),phone=field(input,'phone',30),order=field(input,'order',40,true),category=field(input,'category',40),body=field(input,'body',4000);if(!['شكوى','استفسار عن طلب','استفسار عام'].includes(category))throw new AccountError('نوع الطلب غير صالح.');if(!/^[+\d\s٠-٩۰-۹()-]{7,30}$/.test(phone))throw new AccountError('رقم الهاتف غير صالح.');limitSupport(db,'create:'+hash(phone),5);const id=randomBytes(8).toString('hex'),code=randomBytes(16).toString('hex');db.prepare('INSERT INTO support_tickets(id,access_hash,name,phone,order_ref,category,body) VALUES(?,?,?,?,?,?,?)').run(id,hash(code),name,phone,order,category,body);return {id,code};}
export function ticket(db:DatabaseSync,id:string){const row=db.prepare('SELECT id,name,phone,order_ref,category,body,status,created_at FROM support_tickets WHERE id=?').get(id);if(!row)throw new AccountError('الطلب غير موجود.',404);return {...row,messages:db.prepare('SELECT id,sender,body,created_at FROM support_messages WHERE ticket_id=? ORDER BY id').all(id)};}
export function customerTicket(db:DatabaseSync,id:unknown,code:unknown){if(typeof id!=='string'||typeof code!=='string'||!/^[a-f0-9]{16}$/.test(id)||!/^[a-f0-9]{32}$/.test(code))throw new AccountError('رقم المتابعة أو رمز الوصول غير صحيح.',404);const row=db.prepare('SELECT access_hash FROM support_tickets WHERE id=?').get(id);if(!row||!timingSafeEqual(Buffer.from(hash(code),'hex'),Buffer.from(String(row.access_hash),'hex')))throw new AccountError('رقم المتابعة أو رمز الوصول غير صحيح.',404);return ticket(db,id);}
export function reply(db:DatabaseSync,id:string,sender:'العميل'|'الدعم',body:unknown){if(typeof body!=='string'||!body.trim()||body.trim().length>4000)throw new AccountError('الرسالة مطلوبة وبحد أقصى 4000 حرف.');ticket(db,id);db.prepare('INSERT INTO support_messages(ticket_id,sender,body) VALUES(?,?,?)').run(id,sender,body.trim());if(sender==='العميل')db.prepare("UPDATE support_tickets SET status='قيد المعالجة' WHERE id=?").run(id);}
