'use client';
import {Header,Footer} from '../components';
import {useState,type FormEvent} from 'react';
type Ticket={id:string;name:string;category:string;body:string;status:string;messages:{id:number;sender:string;body:string;created_at:string}[]};
export default function SupportPage(){
 const [mode,setMode]=useState<'create'|'lookup'>('create'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<{id:string;code:string}|null>(null),[current,setCurrent]=useState<Ticket|null>(null),[id,setId]=useState(''),[code,setCode]=useState(''),[message,setMessage]=useState('');
 async function send(body:Record<string,unknown>){const response=await fetch('/api/support',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error||'تعذر إرسال الطلب.');return result;}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{if(mode==='create'){const fields=Object.fromEntries(new FormData(event.currentTarget));const result=await send({...fields,action:'create'});setReceipt(result);setId(result.id);setCode(result.code);}else setCurrent(await send({action:'lookup',id:id.trim(),code:code.trim()}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <><Header/><main className="container" style={{maxWidth:850,padding:'32px 16px'}}><h1>الدعم والشكاوى</h1><p>أرسل استفسارك وسيتابعه فريق المتجر. يمكنك العودة هنا للاطلاع على الرد.</p><div className="title-row"><button className="choice" onClick={()=>{setMode('create');setCurrent(null);setError('');}}>طلب دعم جديد</button><button className="choice" onClick={()=>{setMode('lookup');setError('');}}>متابعة طلب</button></div>
 {receipt&&<section className="notice" role="status"><h2>تم استلام طلبك</h2><p>احتفظ برقم المتابعة والرمز في مكان خاص؛ تحتاج الاثنين لمشاهدة الردود. لا تشارك الرمز مع الآخرين.</p><p>رقم المتابعة: <strong dir="ltr">{receipt.id}</strong></p><p>رمز الوصول: <strong dir="ltr" style={{overflowWrap:'anywhere'}}>{receipt.code}</strong></p><button className="choice" onClick={()=>{setMode('lookup');setReceipt(null);}}>متابعة هذا الطلب</button></section>}
 <form className="panel" onSubmit={submit}><fieldset className="banner-fields formgrid" disabled={busy}>
 {mode==='create'?<><label className="field">الاسم<input name="name" required maxLength={80}/></label><label className="field">رقم الهاتف<input name="phone" type="tel" required maxLength={30}/></label><label className="field">رقم طلب الشراء — اختياري<input name="order" maxLength={40}/></label><label className="field">نوع الطلب<select name="category"><option>شكوى</option><option>استفسار عن طلب</option><option>استفسار عام</option></select></label><label className="field wide">التفاصيل<textarea name="body" required maxLength={4000}/></label></>:<><label className="field">رقم المتابعة<input value={id} onChange={e=>{setId(e.target.value);setCurrent(null);}} required maxLength={16} dir="ltr" autoComplete="off"/></label><label className="field">رمز الوصول<input type="password" value={code} onChange={e=>{setCode(e.target.value);setCurrent(null);}} required maxLength={32} autoComplete="off"/></label></>}
 <button className="btn wide" type="submit">{busy?'جارٍ الإرسال…':mode==='create'?'إرسال طلب الدعم':'عرض الطلب والردود'}</button></fieldset></form>
 {error&&<p className="notice" role="alert">{error}</p>}
 {mode==='lookup'&&current&&<section className="panel"><h2>{current.category} — {current.status}</h2><p style={{whiteSpace:'pre-wrap'}}>{current.body}</p>{current.messages.map(m=><div className="notice" key={m.id}><b>{m.sender}</b><p style={{whiteSpace:'pre-wrap'}}>{m.body}</p><small>{m.created_at} UTC</small></div>)}<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{setCurrent(await send({action:'reply',id:current.id,code:code.trim(),body:message}));setMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label className="field">إضافة رسالة<textarea required maxLength={4000} value={message} onChange={e=>setMessage(e.target.value)}/></label><button disabled={busy} className="btn">إرسال الرد</button></form></section>}
 </main><Footer/></>;
}
